<?php
/**
 * @file
 * Code for the Site Feature feature.
 */

include_once 'site_feature.features.inc';

function site_feature_update_7000(){
  theme_enable(array('gdstheme'));

  $link = db_select('menu_links', 'ml')->fields('ml')->condition('ml.link_title', 'My Dashboard')->execute()->fetchAssoc();
  $link['options'] = unserialize($link['options']);
  $link['hidden'] = 1;
  menu_link_save($link);

  $link = db_select('menu_links', 'ml')->fields('ml')->condition('ml.link_title', 'Standards')->execute()->fetchAssoc();
  $link['options'] = unserialize($link['options']);
  $link['hidden'] = 0;
  menu_link_save($link);
}

function site_feature_update_7001(){
  // Set comments to 'Open'
  db_query('UPDATE {node} JOIN {field_data_field_challenge_status} st ON st.entity_id = node.nid SET node.comment = 2 WHERE st.field_challenge_status_value = 4;')->execute();

  // Migrate challenge status from archived (4) to suggested (0).
  db_update('field_data_field_challenge_status')
    ->fields(array('field_challenge_status_value' => 0))
    ->condition('field_challenge_status_value', 4)
    ->execute();
}


